from django.urls import path
from . import views

urlpatterns=[
    path("", views.index, name="index"),
    path("movie/", views.movie, name="movie"),
    path("tv/", views.tv, name="tv"),
    path("tv/<int:tv_id>/watch/", views.watchtv, name="watchtv"),
    path("movie/<int:movie_id>/watch/", views.watchmov, name="watchmov"),
    path("search/", views.search, name="search"),
    path("home/", views.home, name="home"),
    path("party/", views.party, name="party"),
    path("party/<str:room_code>/", views.party_room, name="party_room"),
    path("category/<slug:slug>/", views.category, name="category"),
    path("<str:type>/<int:id>/", views.detail, name="detail"),
    path("watchlist/", views.watchlist, name="watchlist"),
path("rated/", views.rated, name="rated"),
path("rated/<uuid:user_id>/", views.rated, name="rated_user"),
    path("terms/", views.terms, name="terms"),
    path("dmca/", views.dmca, name="dmca"),
    path("auth/", views.auth, name="auth"),
    path("auth/forgot-password/", views.forgot_password, name="forgot_password"),
    path("auth/reset-password/", views.reset_password, name="reset_password"),
    path("profile/", views.profile, name="profile"),
    path("profile/<uuid:user_id>/", views.public_profile, name="public_profile"),
    path("media-info/<str:type>/<int:id>/", views.media_info, name="media_info"),
    path("aniuzu/", views.aniuzu, name="aniuzu"),
    path("aniuzu/watchlist/", views.aniuzu_watchlist, name="aniuzu_watchlist"),
    path("aniuzu/search/", views.aniuzu_search, name="aniuzu_search"),
    path("aniuzu/anime/<int:anilist_id>/watch/<int:episode>/", views.aniuzu_watch, name="aniuzu_watch"),
    path("aniuzu/continue-metadata/", views.aniuzu_continue_metadata, name="aniuzu_continue_metadata"),
    path("aniuzu/anime/<int:anilist_id>/", views.aniuzu_detail, name="aniuzu_detail"),
    path("aniuzu/genres/", views.aniuzu_genre_list, name="aniuzu_genre_list"),
    path("aniuzu/genres/<str:genre>/", views.aniuzu_genre, name="aniuzu_genre"),
    path("aniuzu/seasons/", views.aniuzu_seasons, name="aniuzu_seasons"),
    path("aniuzu/studios/", views.aniuzu_studios, name="aniuzu_studios"),
    path("aniuzu/studios/<str:studio_name>/", views.aniuzu_studio, name="aniuzu_studio"),
    path("aniuzu/collections/", views.aniuzu_collections, name="aniuzu_collections"),
    path("aniuzu/collections/<str:slug>/", views.aniuzu_collection, name="aniuzu_collection"),
    path("robots.txt", views.robots_txt, name="robots_txt"),
    path("sitemap.xml", views.sitemap_xml, name="sitemap_xml"),

]
